version: "3"
services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - textingApp
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:9001
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    networks:
      - textingApp
    volumes:
      - ./server/src:/usr/app/src
    environment:
      - CLIENT=http://localhost:3000
    command: npm run dev

networks:
  textingApp:
    driver: bridge

volumes:
  mongo-data:
    driver: local
